# UNIT-1

# NUMPY PART-1

# 1. Introduction
# 2. arrays
# 3. arrays are faster than  list
# 4. creating 1d,2d,3d and multi demensional array

# ** Introduction

In [1]:
# numpy stands for numerical python
# numpy is a python libray used forn working with arrays.
# numpy also has functions for working in domain of linear algebra, fourier transform, and matrices
# numpy was created in 2005 by Travis olphant. it is an open source project and you can use it freely


# importance of numpy in python
* vector-vector multiplication
* matrix - matrix and matrix- vector multiplication
* element- wise operationas on vector and matrices (i.e., adding, substracting, multiplying, and deviding by a number )
* Element-wise or array - wise comparisions
* appyling fuctions element- wise to a vector/ matrix(like pow,;og, and exp)
* a whole lot of linear algebra operations can be found in numpy.linalg reduction, statistics, and much more 

# list v/s array

# *  importing library numpy

In [2]:
import numpy as np

In [3]:
x=np.array([1,2,3,4,5,6])
print(x)
print(type(x))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [4]:
l=[1,2,3,4,5,6]
print(l)
print(type(l))

[1, 2, 3, 4, 5, 6]
<class 'list'>


# array is faster than list

In [8]:
%timeit [i**5 for i in range(1,10)]

4.58 µs ± 68.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [10]:
import numpy as np

In [12]:
%timeit np.arange(1,10)**5

3.11 µs ± 154 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# creating numpy arrays

In [18]:
import numpy as np
x=np.array([1,32,36,45])
print(x)
print(type(x))
print(x.ndim)

[ 1 32 36 45]
<class 'numpy.ndarray'>
1


# * creating 2 dimension array

In [23]:
x=np.array([[1,32,36,45]])
print(x)
print(x.ndim)

[[ 1 32 36 45]]
2


# creating 3- d array

In [22]:
x=np.array([[[1,32,36,45]]])
print(x)
print(x.ndim)

[[[ 1 32 36 45]]]
3


# taking inputs from user in a numpy array

In [25]:
import numpy as np
m=[]
for i in range(1,10):
    num=input("enter number")
    m.append(num)
print(np.array(m))
print(type(m))

enter number1
enter number2
enter number3
enter number4
enter number5
enter number6
enter number7
enter number8
enter number9
['1' '2' '3' '4' '5' '6' '7' '8' '9']
<class 'list'>


# * creating 2 dimensional array

In [26]:
ar2=np.array([[1,2,3,4],[5,6,7,8],[10,12,14,16]])
print(ar2)
print(ar2.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [10 12 14 16]]
2


# * creating a 3-d array

In [27]:
ar3=np.array([[[1,2,3,4],[4,5,6,7],[7,8,9,10]]])
print(ar3)
print(ar3.ndim)

[[[ 1  2  3  4]
  [ 4  5  6  7]
  [ 7  8  9 10]]]
3


# creating a multi dimensional array

In [30]:
x=np.array([1,2,5,6], ndmin=15)
print(x)
print(x.ndim)

[[[[[[[[[[[[[[[1 2 5 6]]]]]]]]]]]]]]]
15


In [31]:
x=np.array([1,2,5,6], ndmin=2)
print(x)
print(x.ndim)

[[1 2 5 6]]
2


# NUMPY PART=2

# 1. special numpy array
# 2. creating an empty array
# 3. range in array
# 4. linspace, shape, reshape
# 5. ravel and flatten
# 6. identity matrix
# 7. rand()
# 8. randn()
# 9. randint()
# 10. randf()

# ** special numpy array
* numpy array with all its elements value as zero(using zeros()) function of numpy
* numpy array with its all elements value as one(using ones() function of numpy)
* creating an empty array
* numpy array with all its elements values as a specific given value(using full() function of numpy)
* identity matrix or array

# ** numpy array with all its elements value as zero

In [1]:
import numpy as np

In [3]:
ar=np.zeros(5)
print(ar)
print(ar.ndim)
print(type(ar))

[0. 0. 0. 0. 0.]
1
<class 'numpy.ndarray'>


In [4]:
ar1=np.zeros((4,3))
print(ar1)
print(ar1.ndim)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
2


In [5]:
ar2=np.zeros((1,3,4))
print(ar2)
print(ar2.ndim)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
3


In [6]:
ar2=np.zeros((2,3,4))
print(ar2)
print(ar2.ndim)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
3


# *numpy array with its all elements value as one

In [8]:
arr=np.ones(6)
print(arr)
print(type(arr))
print(arr.ndim)

[1. 1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
1


# 2-d array

In [9]:
arr1=np.ones((4,5))
print(arr1)
print(arr1.ndim)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
2


# 3- d rray

In [11]:
arr2=np.ones((1,3,3))
print(arr2)
print(arr2.ndim)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
3


In [12]:
arr2=np.ones((3,3,3))
print(arr2)
print(arr2.ndim)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
3


# ** changing data type of the array

In [13]:
arr2=np.ones((3,3,3),dtype="bool")
print(arr2)
print(arr2.ndim)

[[[ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]
  [ True  True  True]]]
3


# ** creating an empty array

In [15]:
k=np.empty(3)
print(k)
print(type(k))
print(k.ndim)

[0. 0. 0.]
<class 'numpy.ndarray'>
1


# 2-d array

In [18]:
m=np.empty((4,3))
print(m)
print(m.ndim)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
2


# ** creating an array with range

In [20]:
b=np.arange(1,21)
print(b)
print(b.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
1


In [21]:
c=np.arange(3,101)
print(c)
print(c.ndim)

[  3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19  20
  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38
  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56
  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74
  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92
  93  94  95  96  97  98  99 100]
1


In [22]:
c=np.arange(3,101,3)
print(c)
print(c.ndim)

[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]
1


In [24]:
c=np.arange(5,1001,5)
print(c)
print(c.ndim)

[   5   10   15   20   25   30   35   40   45   50   55   60   65   70
   75   80   85   90   95  100  105  110  115  120  125  130  135  140
  145  150  155  160  165  170  175  180  185  190  195  200  205  210
  215  220  225  230  235  240  245  250  255  260  265  270  275  280
  285  290  295  300  305  310  315  320  325  330  335  340  345  350
  355  360  365  370  375  380  385  390  395  400  405  410  415  420
  425  430  435  440  445  450  455  460  465  470  475  480  485  490
  495  500  505  510  515  520  525  530  535  540  545  550  555  560
  565  570  575  580  585  590  595  600  605  610  615  620  625  630
  635  640  645  650  655  660  665  670  675  680  685  690  695  700
  705  710  715  720  725  730  735  740  745  750  755  760  765  770
  775  780  785  790  795  800  805  810  815  820  825  830  835  840
  845  850  855  860  865  870  875  880  885  890  895  900  905  910
  915  920  925  930  935  940  945  950  955  960  965  970  975  980
  985 

# ** linspace() function

In [25]:
a=np.linspace(1,10,5)
print(a)
print(a.ndim)

[ 1.    3.25  5.5   7.75 10.  ]
1


In [26]:
a=np.linspace(1,30,8)
print(a)
print(a.ndim)

[ 1.          5.14285714  9.28571429 13.42857143 17.57142857 21.71428571
 25.85714286 30.        ]
1


In [27]:
a=np.linspace(5,20,6)
print(a)
print(a.ndim)

[ 5.  8. 11. 14. 17. 20.]
1


# * shape () fucntion

In [29]:
ar=np.array([[1,2,3],[10,11,13]])
print(ar)
print(ar.ndim)
print(ar.shape)

[[ 1  2  3]
 [10 11 13]]
2
(2, 3)


In [30]:
ar=np.array([[1,2,3],[10,11,13],[15,16,17]])
print(ar)
print(ar.ndim)
print(ar.shape)

[[ 1  2  3]
 [10 11 13]
 [15 16 17]]
2
(3, 3)


In [31]:
ar=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
print(ar)
print(ar.shape)
print(ar.ndim)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]
(1, 4, 3)
3


In [3]:
import numpy as np

# ** reshape

In [5]:
m=np.array([1,2,3,4,5,6,7,8,9,10])
n=m.reshape(2,5)
print(n)
print()
print(m)
print(n.ndim)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

[ 1  2  3  4  5  6  7  8  9 10]
2


In [6]:
m=np.array([1,2,3,4,5,6,7,8,9,10])
n=m.reshape(3,3)
print(n)
print()
print(m)
print(n.ndim)

ValueError: cannot reshape array of size 10 into shape (3,3)

# * converting one dimension into 3 dimension

In [7]:
m=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18])
n=m.reshape(3,2,3)
print(n)
print()
print(m)
print(n.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
3


In [8]:
m=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18])
n=m.reshape(2,2,3)
print(n)
print()
print(m)
print(n.ndim)

ValueError: cannot reshape array of size 18 into shape (2,2,3)

In [9]:
# converting two dimension into 4 dimension

In [12]:
x=np.array([[1,2,3,8],[4,5,6,20],[7,8,9,21]])
print(x.ndim)
print(x)
print()
y=x.reshape(2,1,2,3)
print(y)
print(y.ndim)

2
[[ 1  2  3  8]
 [ 4  5  6 20]
 [ 7  8  9 21]]

[[[[ 1  2  3]
   [ 8  4  5]]]


 [[[ 6 20  7]
   [ 8  9 21]]]]
4


# * ravel and flatten function

In [13]:
# convert multidimensional into one dim array

In [18]:
m=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(m)
print("dimensions is:",m.ndim)
print()
n=m.ravel()
print(n)
print("now the new dimension is:",n.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
dimensions is: 3

[1 2 3 4 5 6 7 8 9]
now the new dimension is: 1


In [19]:
m=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(m)
print("dimensions is:",m.ndim)
print()
n=m.flatten()
print(n)
print("now the new dimension is:",n.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
dimensions is: 3

[1 2 3 4 5 6 7 8 9]
now the new dimension is: 1


In [22]:
c=np.array([[[[1,2,3],[78,89,25],[45,26,84]]]])
print("the old dimension is:",c.ndim)
print(c)
print()
d=c.flatten()
print(d)
print("the new dimension is:",d.ndim)

the old dimension is: 4
[[[[ 1  2  3]
   [78 89 25]
   [45 26 84]]]]

[ 1  2  3 78 89 25 45 26 84]
the new dimension is: 1


In [23]:
c=np.array([[[[1,2,3],[78,89,25],[45,26,84]]]])
print("the old dimension is:",c.ndim)
print(c)
print()
d=c.ravel()
print(d)
print("the new dimension is:",d.ndim)

the old dimension is: 4
[[[[ 1  2  3]
   [78 89 25]
   [45 26 84]]]]

[ 1  2  3 78 89 25 45 26 84]
the new dimension is: 1


# create an array with diagonal elements filled with 1- identity matrix

In [24]:
arr=np.eye(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [25]:
ar1=np.eye(3,6)
print(ar1)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]


In [26]:
ar1=np.eye(5,8)
print(ar1)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]]


# * rand() function

In [27]:
# it creates an array with random floating point numbers between 0 and 1

In [30]:
var=np.random.rand(5)
print(var)

[0.67659669 0.80906632 0.64915583 0.29057146 0.91400208]


In [ ]:
[0.82723429 0.32375635 0.24541065 0.19898695 0.38193969]

In [32]:
var=np.random.rand(3,4)
print(var)

[[0.10012432 0.55453568 0.3371512  0.51370968]
 [0.02399263 0.51833912 0.36937669 0.52608081]
 [0.60716475 0.64228648 0.79395561 0.82007656]]


In [33]:
var=np.random.rand(2,3,4)
print(var)

[[[0.19915983 0.82996699 0.27506144 0.88094042]
  [0.86859312 0.8220141  0.63730673 0.47953885]
  [0.28518039 0.2712983  0.84826062 0.14347716]]

 [[0.01345859 0.53416874 0.79651367 0.05614312]
  [0.65343005 0.26186094 0.00695281 0.30370567]
  [0.97200304 0.946531   0.51466007 0.26861537]]]


# * randn() function
the function is used to generate a value close to zero and this may return positive as well as negative numbers as well

In [36]:
n=np.random.randn(5)
print(n)
print("the dimension is:",n.ndim)

[-1.27727847 -0.70053001 -1.05376995 -0.38235625 -1.14470273]
the dimension is: 1


In [ ]:
[-0.65747741  0.01122573 -0.56288749 -1.64759275 -0.33663341]
the dimension is: 1

In [38]:
n=np.random.randn(2,5)
print(n)
print(n.ndim)
print(n.shape)

[[-0.6706746   0.21942252 -0.87098283  0.55971084 -1.47032391]
 [ 0.29262794  0.13821677 -0.32106654  1.56085477  1.81844779]]
2
(2, 5)


In [39]:
n=np.random.randn(1,2,5)
print(n)
print(n.ndim)
print(n.shape)

[[[-0.14620292 -0.77455207 -1.01321764  0.6330242  -0.40288678]
  [ 0.63428843 -1.33162821 -1.36134418 -0.04841752 -0.84839395]]]
3
(1, 2, 5)


# ** randint()


In [ ]:
# it gives random integers between the given parameters

In [43]:
a=np.random.randint(4,20,5)
print(a)
print(a.ndim)

[ 6 16 15 16 18]
1


In [44]:
a=np.random.randint(4,20,8)
print(a)
print(a.ndim)

[ 9 11  8 12 18 13  6 16]
1


# ** ranf()

# this function is used for doing random sampling in numpy it returnns an array and specified shape and fills it with random floats in the half open interval between zero and one

In [46]:
x=np.random.ranf(4)
print(x)

[0.73881336 0.21171776 0.96129069 0.9452617 ]


In [48]:
x=np.random.ranf((2,4))
print(x)

[[0.39941411 0.8621206  0.72057991 0.24628552]
 [0.65731577 0.27457582 0.15566017 0.31803735]]


# NUMPY PART-3

# 1. data types
# 2. convert
# 3. arithmetic operations(+,-,*,/,%,reciprocal)
# 4. arithmatic function
# 5. min, max
# 6. square root
# 7. sin value, cos value
# 8. broadcasting
# 9. cumsum

# ** Data types in numpy

In [2]:
import numpy as np

In [3]:
x=np.array([1,2,3,4])
print("the data types is:",x.dtype)

the data types is: int32


In [4]:
x1=np.array([2.5,8.6,9.5,4.1,7.3])
print("the data type sis:",x1.dtype)

the data type sis: float64


In [5]:
x2=np.array(["apple","c","dog","horse","random"])
print("the data type sis:",x2.dtype)

the data type sis: <U6


# converting one data type into another data type

In [7]:
x=np.array([1,2,3,4,5],dtype='int16')
print(x)
print(x.dtype)

[1 2 3 4 5]
int16


In [8]:
x=np.array([1,2,3,4,5],dtype='float64')
print(x)
print(x.dtype)

[1. 2. 3. 4. 5.]
float64


In [9]:
x=np.array([1,2,3,4,5],dtype='f')
print(x)
print(x.dtype)

[1. 2. 3. 4. 5.]
float32


In [12]:
x=np.array([1,2,3,4,5],dtype='float64')
print(x)
print(x.dtype)

x2=np.int64(x)
print(x2)
print(x2.dtype)

[1. 2. 3. 4. 5.]
float64
[1 2 3 4 5]
int64


In [13]:
x=np.array([1,2,3,4],dtype="complex")
print(x)
print(x.dtype)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j]
complex128


# arithmatic operations in numpy array

1. addition

In [14]:
x=np.array([1,2,3,4,5])
y=x+3
print(y)

[4 5 6 7 8]


In [15]:
x=np.array([1,2,3,4,5])
m=np.array([5,6,7,8,9])
y=x+m
print(y)

[ 6  8 10 12 14]


In [16]:
x=np.array([1,2,3,4,5])
m=np.array([5,6,7,8,9])
y=np.add(x,m)
print(y)

[ 6  8 10 12 14]


2. subtraction

In [17]:
x=np.array([1,2,3,4,5])
y=x-3
print(y)

[-2 -1  0  1  2]


In [18]:
x=np.array([1,2,3,4,5])
m=np.array([5,6,7,8,9])
y=np.subtract(x,m)
print(y)

[-4 -4 -4 -4 -4]


In [19]:
x=np.array([1,2,3,4,5])
m=np.array([5,6,7,8,9])
y=np.subtract(m,x)
print(y)

[4 4 4 4 4]


In [20]:
x=np.array([1,2,3,4,5])
m=np.array([5,6,7,8,9])
y=x-m
print(y)

[-4 -4 -4 -4 -4]


3. multiplication

In [21]:
x=np.array([1,2,3,4])
y=x*3
print(y)

[ 3  6  9 12]


In [23]:
x=np.array([1,2,3,4,5])
m=np.array([5,6,7,8,9])
y=np.multiply(m,x)
print(y)

[ 5 12 21 32 45]


4. division

In [24]:
x=np.array([1,2,3,4])
y=x/3
print(y)

[0.33333333 0.66666667 1.         1.33333333]


In [25]:
x=np.array([1,2,3,4,5])
m=np.array([5,6,7,8,9])
y=np.divide(m,x)
print(y)

[5.         3.         2.33333333 2.         1.8       ]


5. modulus

In [26]:
x=np.array([10,15,25,30])
y=x%3
print(y)

[1 0 1 0]


In [29]:
x=np.array([1,2,3,4,5])
m=np.array([5,6,7,8,9])
y=np.mod(m,x)
print(y)

[0 0 1 0 4]


# 6. reciprocal

In [30]:
a=np.array([23,25,28,32])
b=np.reciprocal(a)
print(b)

[0 0 0 0]


# arithmatic operations in 2-D array

1. addition

In [34]:
n1=np.array([[1,2,3,4],[5,6,7,8]])
n2=np.array([[1,2,3,4],[5,6,7,8]])
x=np.add(n1,n2)
print(x)

[[ 2  4  6  8]
 [10 12 14 16]]


In [35]:
n1=np.array([[1,2,3,4],[5,6,7,8]])
n2=np.array([[1,2,3,4],[5,6,7,8]])
x=n1+n2
print(x)

[[ 2  4  6  8]
 [10 12 14 16]]


 2. substraction

In [36]:
n1=np.array([[1,2,3,4],[5,6,7,8]])
n2=np.array([[1,2,3,4],[5,6,7,8]])
x=np.subtract(n1,n2)
print(x)

[[0 0 0 0]
 [0 0 0 0]]


 3. multiplication

In [37]:
n1=np.array([[1,2,3,4],[5,6,7,8]])
n2=np.array([[1,2,3,4],[5,6,7,8]])
x=np.multiply(n1,n2)
print(x)

[[ 1  4  9 16]
 [25 36 49 64]]


 4. divisuion

In [42]:
n1=np.array([[1,2,3,4],[5,6,7,8]])
n2=np.array([[1,2,3,4],[5,6,7,8]])
x=np.divide(n1,n2)
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# arithmatic operations in 3-D array

1. addition

In [44]:
n1=np.array([[[1,2,3,4],[5,6,7,8]]])
n2=np.array([[[1,2,3,4],[5,6,7,8]]])
x=np.add(n1,n2)
print(x.ndim)
print(x)

3
[[[ 2  4  6  8]
  [10 12 14 16]]]


2. substraction

In [46]:
n1=np.array([[[1,2,3,4],[5,6,7,8]]])
n2=np.array([[[1,2,3,4],[5,6,7,8]]])
x=np.subtract(n1,n2)
print(x.ndim)
print(x)

3
[[[0 0 0 0]
  [0 0 0 0]]]


3. multiplication

In [47]:
n1=np.array([[[1,2,3,4],[5,6,7,8]]])
n2=np.array([[[1,2,3,4],[5,6,7,8]]])
x=np.multiply(n1,n2)
print(x.ndim)
print(x)

3
[[[ 1  4  9 16]
  [25 36 49 64]]]


4. division

In [49]:
n1=np.array([[[1,2,3,4],[5,6,7,8]]])
n2=np.array([[[1,2,3,4],[5,6,7,8]]])
x=np.divide(n1,n2)
print(x.ndim)
print(x)

3
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


# arithmetic functions

# max and min along with the index number

In [1]:
import numpy as np

In [2]:
a=np.array([12,13,1,2,3,5,8,5,4,78])
print(np.max(a))
print(np.min(a))

78
1


In [3]:
a=np.array([12,13,1,2,3,5,8,5,4,78])
print(np.max(a),np.argmax(a))
print(np.min(a),np.argmin(a))


78 9
1 2


In [12]:
m=np.array([[1,15,32,78,96],[14,25,100,96,35]])
print(m.ndim)
print(m)
n=np.min(m,axis=0)
print(n)

p=np.max(m,axis=0)
print(p)

2
[[  1  15  32  78  96]
 [ 14  25 100  96  35]]
[ 1 15 32 78 35]
[ 14  25 100  96  96]


In [13]:
m=np.array([[1,15,32,78,96],[14,25,100,96,35]])
print(m.ndim)
print(m)
n=np.min(m,axis=1)
print(n)

p=np.max(m,axis=1)
print(p)

2
[[  1  15  32  78  96]
 [ 14  25 100  96  35]]
[ 1 14]
[ 96 100]


# * square root

In [14]:
a=np.array([12,13,21,12,16,4])
print(np.sqrt(a))

[3.46410162 3.60555128 4.58257569 3.46410162 4.         2.        ]


In [16]:
a=np.array([[12,13,21,12,16,4],[9,64,25,30,49,81]])
print(np.sqrt(a))

[[3.46410162 3.60555128 4.58257569 3.46410162 4.         2.        ]
 [3.         8.         5.         5.47722558 7.         9.        ]]


# sin value and cos value

In [17]:
a=np.array([1,2,3])
print(np.sin(a))

[0.84147098 0.90929743 0.14112001]


In [18]:
a=np.array([1,2,3])
print(np.cos(a))

[ 0.54030231 -0.41614684 -0.9899925 ]


In [19]:
a=np.array([[1,2,3],[4,5,6],[8,9,10]])
print(np.sin(a))

[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.98935825  0.41211849 -0.54402111]]


In [20]:
a=np.array([[1,2,3],[4,5,6],[8,9,10]])
print(np.cos(a))

[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]
 [-0.14550003 -0.91113026 -0.83907153]]


# cumsum

In [21]:
# cum-cummalative, sum- addition

In [22]:
a=np.array([1,2,3,4])
print(np.cumsum(a))

[ 1  3  6 10]


In [23]:
a=np.array([[1,2,3,4],[5,6,7,8]])
print(np.cumsum(a))

[ 1  3  6 10 15 21 28 36]


# Broadcasting in numpy array

In [1]:
import numpy as np

In [2]:
n1=np.array([1,2,3,4])
n2=np.array([2,3,5])
x=n1+n2
print(x)

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [5]:
n1=np.array([1,2,3,4])
print(n1.shape)
print(n1)
n2

print()
n2=np.array([[1],[2],[3],[4]])
print(n2.shape)
print(n2)

print("the broadcasting array is here:")
print(n1+n2)

(4,)
[1 2 3 4]

(4, 1)
[[1]
 [2]
 [3]
 [4]]
the broadcasting array is here:
[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]]


In [10]:
x=np.array([[4],[3]])
print(x.shape)
print(x)
print()
y=np.array([[6,7,3],[1,3,2]])
print(y.shape)
print(y)
print("the broadcasting array is:")
print(x+y)
print()
print(x-y)
print()
print(x*y)
print()
print(x/y)
print()

(2, 1)
[[4]
 [3]]

(2, 3)
[[6 7 3]
 [1 3 2]]
the broadcasting array is:
[[10 11  7]
 [ 4  6  5]]

[[-2 -3  1]
 [ 2  0  1]]

[[24 28 12]
 [ 3  9  6]]

[[0.66666667 0.57142857 1.33333333]
 [3.         1.         1.5       ]]



In [14]:
x=np.array([[4,8],[3,7],[5,9]])
print(x.shape)
print(x)
print()
y=np.array([[6,7],[1,3]])
print(y.shape)
print(y)
print("the broadcasting array is:")
print(x+y)

(3, 2)
[[4 8]
 [3 7]
 [5 9]]

(2, 2)
[[6 7]
 [1 3]]
the broadcasting array is:


ValueError: operands could not be broadcast together with shapes (3,2) (2,2) 

In [ ]:
#** row same