# numpy part-4

# 1. indexing in numpy array
# 2. slicing in  numpy array


# *1. indexing in numpy array

In [3]:
import numpy as np

In [4]:
x=np.array([10,11,12,14,15,45])
print(x[4])

15


In [5]:
x=np.array([10,11,12,14,15,45])
print(x[-1])

45


In [8]:
x=np.array([10,11,12,14,15,45])
print(x[-3])

14


# * indexing in 2D array

In [10]:
x=np.array([[11,12],[13,14]])
print(x[0,1])

12


In [11]:
x=np.array([[4,5,6],[10,11,12],[13,14,15]])
print(x[1,1])

11


In [12]:
print(x[2,1])

14


# * indexing in 3D array in numpy

In [21]:
x=np.array([[[11,12],[13,14]],[[15,16],[17,18]]])
print(x)
print(x.ndim)
print(x[1,0,1])

[[[11 12]
  [13 14]]

 [[15 16]
  [17 18]]]
3
16


In [25]:
x=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(x[0,1,2])
           

6


In [1]:
import numpy as np

In [2]:
a=np.array([[[[[1,2,3],[4,5,6],[7,8,9]]]]])
print(a)
print(a.ndim)

[[[[[1 2 3]
    [4 5 6]
    [7 8 9]]]]]
5


In [4]:
print(a[0,0,0,1,1])

5


# * Slicing of numpy array

# 1.slicing in 1-D array

In [8]:
a=np.array([11,12,13,14,15,16,17,18,19])
b=a[2:7]
print(b)
print(b.ndim)
print(type(b))

[13 14 15 16 17]
1
<class 'numpy.ndarray'>


In [9]:
a=np.array([11,12,13,14,15,16,17,18,19])
b=a[2:7:2]
print(b)
print(b.ndim)
print(type(b))

[13 15 17]
1
<class 'numpy.ndarray'>


In [10]:
a=np.array([11,12,13,14,15,16,17,18,19])   ## reverse a numpy array
print(a[::-1])

[19 18 17 16 15 14 13 12 11]


# * Slicing in 2D numpy array

In [14]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
x=a[1,1:4]
print(x)


[7 8 9]


In [15]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
y=a[0,1:4]
print(y)

[2 3 4]


In [17]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
x=a[1,0::2]
print(x)

[ 6  8 10]


In [19]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
x=a[1,::-1]
print(x)

[10  9  8  7  6]


# * Slicing in 3D numpy array

In [20]:
a=np.array([[[1,2,3,7,9],[4,5,6,9,10],[7,8,9,1,2]]])
x=a[0,1,1:4]
print(x)

[5 6 9]


In [21]:
x=a[0,0,2::]
print(x)

[3 7 9]


# NUMPY PART-5

# 1. iterating numpy arrays(1D,2D,3D)
# 2. nditer()
# 3. ndenumerate()
# 4. copy v/s view
# 5. join arrays --> concatenate


# * iteraring numpy arrays

In [1]:
import numpy as np

In [4]:
a=np.array([1,2,3,4,5])
print(a.ndim)
for i in a:
    print(i)

1
1
2
3
4
5


# 2D array

In [10]:
x=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(x)
print(x.ndim)
print()
for i in x:
    for j in i:
        print(j)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2

1
2
3
4
5
6
7
8
9
10


# 3D array

In [12]:
x=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print(x.ndim)
print(x)


for i in x:
    for j in i:
        for k in j:
            print(k)

3
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
1
2
3
4
5
6
7
8
9
10
11
12


# * nditer function

In [17]:
x=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print(x)
print(x.ndim)

for i in np.nditer(x):
    print(i)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
3
1
2
3
4
5
6
7
8
9
10
11
12


In [18]:
# for changing the data type of the array
x=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print(x)
print(x.ndim)

for i in np.nditer(x,flags=['buffered'],op_dtypes=['S']):
    print(i)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
3
b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
b'8'
b'9'
b'10'
b'11'
b'12'


# to know the index of the elements of the numpy array

# ndenumerate function

In [19]:
x=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
for i in np.ndenumerate(x):
    print(i)

((0, 0, 0), 1)
((0, 0, 1), 2)
((0, 0, 2), 3)
((0, 0, 3), 4)
((0, 1, 0), 5)
((0, 1, 1), 6)
((0, 1, 2), 7)
((0, 1, 3), 8)
((0, 2, 0), 9)
((0, 2, 1), 10)
((0, 2, 2), 11)
((0, 2, 3), 12)


In [22]:
a=np.array([[[[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]]]])
print(a.ndim)
print(a)

for i in np.ndenumerate(a):
    print("the numers are:",i)

5
[[[[[ 1  2  3  4  5]
    [ 6  7  8  9 10]
    [11 12 13 14 15]]]]]
the numers are: ((0, 0, 0, 0, 0), 1)
the numers are: ((0, 0, 0, 0, 1), 2)
the numers are: ((0, 0, 0, 0, 2), 3)
the numers are: ((0, 0, 0, 0, 3), 4)
the numers are: ((0, 0, 0, 0, 4), 5)
the numers are: ((0, 0, 0, 1, 0), 6)
the numers are: ((0, 0, 0, 1, 1), 7)
the numers are: ((0, 0, 0, 1, 2), 8)
the numers are: ((0, 0, 0, 1, 3), 9)
the numers are: ((0, 0, 0, 1, 4), 10)
the numers are: ((0, 0, 0, 2, 0), 11)
the numers are: ((0, 0, 0, 2, 1), 12)
the numers are: ((0, 0, 0, 2, 2), 13)
the numers are: ((0, 0, 0, 2, 3), 14)
the numers are: ((0, 0, 0, 2, 4), 15)


# * Copy V/S View Function

In [24]:
x=np.array([1,2,3,4,5,6])  # changes shown in both the array
y=x.view()  ## no new array is form
x[4]=56
print(y)
print()
print(x)

[ 1  2  3  4 56  6]

[ 1  2  3  4 56  6]


In [25]:
x=np.array([1,2,3,4,5,6])  # changes shown in only in one array
y=x.copy()                 # new array is form
x[4]=56
print(y)
print()
print(x)

[1 2 3 4 5 6]

[ 1  2  3  4 56  6]


# * Join  numpy array
1. concatenate function

In [28]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])

c=np.concatenate((a,b))
print(c)

[ 1  2  3  4  5  6  7  8  9 10]


In [33]:
a=np.array([[1,2,3,4,5],[10,20,30,40,50]])
print(a)
print()
b=np.array([[6,7,8,9,10],[60,70,80,90,100]])
print()
print(b)
print()
c=np.concatenate((a,b),axis=0)
print(c)
print()
c=np.concatenate((a,b),axis=1)
print(c)

[[ 1  2  3  4  5]
 [10 20 30 40 50]]


[[  6   7   8   9  10]
 [ 60  70  80  90 100]]

[[  1   2   3   4   5]
 [ 10  20  30  40  50]
 [  6   7   8   9  10]
 [ 60  70  80  90 100]]

[[  1   2   3   4   5   6   7   8   9  10]
 [ 10  20  30  40  50  60  70  80  90 100]]


# *stack function is used to joining of two numpy arrays

# . stack function
1. hstack(rows)--> horizontally
2. vstack(columns)---> vertically
3. dstack(height)---> diognally

In [40]:
x=np.array([1,2,3,4])
x1=np.array([5,6,7,8])
x2=np.array([100,200,300,400])
print("this is array")
print("the array x:",x)
print()
print("the array x1:",x1)
print()
print("the array x2",x2)

print()

v=np.hstack((x,x1,x2))
print("the horizontally joined arra is:",v)
print()
q=np.vstack((x,x1,x2))
print("the vertically jined array is:",q)
print()
r=np.dstack((x,x1,x2))
print("the diognally joined array is: ",r)

this is array
the array x: [1 2 3 4]

the array x1: [5 6 7 8]

the array x2 [100 200 300 400]

the horizontally joined arra is: [  1   2   3   4   5   6   7   8 100 200 300 400]

the vertically jined array is: [[  1   2   3   4]
 [  5   6   7   8]
 [100 200 300 400]]

the diognally joined array is:  [[[  1   5 100]
  [  2   6 200]
  [  3   7 300]
  [  4   8 400]]]


# NUMPY PART-6

# functions in numpy
1. split array
2. search
3. search sorted array
4. sort array
5. filter array
6. shuffle function
7.unique function
8.resize 
9. insert function
10. append
11. delete

# 1. SPLIT NUMPY ARRAY

In [1]:
import numpy as np

In [4]:
a=np.array([1,2,3,4,5,6,7,8,9])
print(a)

print()
v=np.array_split(a,3)
print("the splited arra is :",v)
print(type(v))

[1 2 3 4 5 6 7 8 9]

the splited arra is : [array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
<class 'list'>


In [6]:
print(v[0])

[1 2 3]


# * split in 2D array

In [9]:
a=np.array([[1,2],[4,5],[6,7],[8,9]])   # use axis to split the array
print(a)
v=np.array_split(a,4,axis=1)
print(v)

[[1 2]
 [4 5]
 [6 7]
 [8 9]]
[array([[1],
       [4],
       [6],
       [8]]), array([[2],
       [5],
       [7],
       [9]]), array([], shape=(4, 0), dtype=int32), array([], shape=(4, 0), dtype=int32)]


In [10]:
a=np.array([[1,2],[4,5],[6,7],[8,9]])   # use axis to split the array
print(a)
v=np.array_split(a,4,axis=0)
print(v)

[[1 2]
 [4 5]
 [6 7]
 [8 9]]
[array([[1, 2]]), array([[4, 5]]), array([[6, 7]]), array([[8, 9]])]


In [12]:
a=np.array([[1,2],[4,5],[6,7],[8,9]])   # use axis to split the array
print(a)
v=np.array_split(a,2,axis=0)
print(v)

[[1 2]
 [4 5]
 [6 7]
 [8 9]]
[array([[1, 2],
       [4, 5]]), array([[6, 7],
       [8, 9]])]


# * 2.searching in numpy array
using where function

In [13]:
import numpy as np

In [14]:
a=np.array([1,2,7,9,6,4,3,7,6,0])
x=np.where(a==3)
print(x)

(array([6], dtype=int64),)


In [15]:
a=np.array([1,2,7,9,6,4,3,7,6,0])
x=np.where(a%2==0)
print(x)

(array([1, 4, 5, 8, 9], dtype=int64),)


# *3. search sorted array

In [16]:
a=np.array([11,12,13,14,18,19,22,23])
x=np.searchsorted(a,15)
print(x)

4


In [18]:
a=np.array([11,12,13,14,18,19,22,23])
x=np.searchsorted(a,20)
print(x)

6


In [19]:
a=np.array([11,12,13,14,18,19,22,23])
x=np.searchsorted(a,20,side='right')
print(x)

6


In [20]:
a=np.array([11,12,13,14,18,19,22,23])
x=np.searchsorted(a,20,side='left')
print(x)

6


In [21]:
a=np.array([21,22,23,31,32,33])
x=np.searchsorted(a,[25,28,30])
print(x)

[3 3 3]


# *4 sorting of numpy array
in one dimension

In [24]:
a=np.array([22,45,63,21,20,4,6,-2,-1])
x=np.sort(a)
print(x)

[-2 -1  4  6 20 21 22 45 63]


In [25]:
b=np.array(["o","k","w","q","z","a","n","p","v"])
print(np.sort(b))

['a' 'k' 'n' 'o' 'p' 'q' 'v' 'w' 'z']


# * sorting in 2D array

In [33]:
a=np.array([[22,45,63,21],[20,4,6,-1]])
print(a.ndim)
print(a)
print()
x=np.sort(a)
print(x)

2
[[22 45 63 21]
 [20  4  6 -1]]

[[21 22 45 63]
 [-1  4  6 20]]


# * sorting in 3D array

In [37]:
x=np.array([[[14,18,-9],[-2,36,15],[12,89,-100]]])
print(x)
print(x.ndim)
print()
y=np.sort(x)
print("the sorted array is:",y)

[[[  14   18   -9]
  [  -2   36   15]
  [  12   89 -100]]]
3

the sorted array is: [[[  -9   14   18]
  [  -2   15   36]
  [-100   12   89]]]


# * Filter array
 we choose which elements we want to keep or which is not

In [39]:
x=np.array([15,78,96,14,66])
f=[True,False,False,True,False]

b=x[f]
print(b)

[15 14]


# * Shuffle function()
to shuffle elements randomly like cards shuffling

In [44]:
k=np.array([14,12,13,18,26,47,96])
print(k)
np.random.shuffle(k)
print("the array after shuffling:",k)


[14 12 13 18 26 47 96]
the array after shuffling: [13 26 12 14 47 18 96]


# * unique function()

In [46]:
x=np.array([12,14,6,7,9,3,45,5,33,2,33,2,33,14,12,7,9])
print(x)
print()
y=np.unique(x)
print(y)

[12 14  6  7  9  3 45  5 33  2 33  2 33 14 12  7  9]

[ 2  3  5  6  7  9 12 14 33 45]


In [47]:
x=np.array([12,14,6,7,9,3,45,5,33,2,33,2,33,14,12,7,9])
print(x)
print()
y=np.unique(x,return_index=True)
print(y)

[12 14  6  7  9  3 45  5 33  2 33  2 33 14 12  7  9]

(array([ 2,  3,  5,  6,  7,  9, 12, 14, 33, 45]), array([9, 5, 7, 2, 3, 4, 0, 1, 8, 6], dtype=int64))


In [48]:
x=np.array([12,14,6,7,9,3,45,5,33,2,33,2,33,14,12,7,9])
print(x)
print()
y=np.unique(x,return_index=True,return_counts=True)
print(y)

[12 14  6  7  9  3 45  5 33  2 33  2 33 14 12  7  9]

(array([ 2,  3,  5,  6,  7,  9, 12, 14, 33, 45]), array([9, 5, 7, 2, 3, 4, 0, 1, 8, 6], dtype=int64), array([2, 1, 1, 1, 2, 2, 2, 2, 3, 1], dtype=int64))


# * resize in numpy array

In [50]:
a=np.array([1,2,3,4,5,6,7,8,9])
print(a)
print(a.ndim)
print(a.shape)
b=np.resize(a,(3,2))
print("now the size is:")
print(b)
print("the dimension is:",b.ndim)
print("the shape is",b.shape)

[1 2 3 4 5 6 7 8 9]
1
(9,)
now the size is:
[[1 2]
 [3 4]
 [5 6]]
the dimension is: 2
the shape is (3, 2)


# * insert function

In [52]:
n=np.array([1,2,3,4,5])
print(n)
print(n.shape)
b=np.insert(n,3,200)
print(b)

[1 2 3 4 5]
(5,)
[  1   2   3 200   4   5]


In [53]:
n=np.array([1,2,3,4,5])
print(n)
print(n.shape)
b=np.insert(n,(3,5),(20,40))
print(b)

[1 2 3 4 5]
(5,)
[ 1  2  3 20  4  5 40]


# * insertion in 2D array

In [2]:
import numpy as np
a=np.array([[2,7,9,6,8],[4,5,7,1,2]])
print(a)

[[2 7 9 6 8]
 [4 5 7 1 2]]


In [4]:
# use axis to insert in 2D array
x1=np.insert(a,2,24,axis=1)
print(x1)

[[ 2  7 24  9  6  8]
 [ 4  5 24  7  1  2]]


In [5]:
x1=np.insert(a,2,24,axis=0)
print(x1)

[[ 2  7  9  6  8]
 [ 4  5  7  1  2]
 [24 24 24 24 24]]


# * multiple number insert in 2D array

In [7]:
x1=np.insert(a,2,[24,25,26,28,29],axis=0)
print(x1)

[[ 2  7  9  6  8]
 [ 4  5  7  1  2]
 [24 25 26 28 29]]


# * APPEND FUNCTION()

In [8]:
import numpy as np

In [9]:
a=np.array([12,13,14])
x=np.append(a,3.25)
print(x)

[12.   13.   14.    3.25]


# * 2D array

In [10]:
x=np.array([[2,7,9,6,8],[4,5,7,1,2]])
m=np.append(x,[[-4,-5,-6,-7,-8]],axis=0)
print(x)
print()
print(m)

[[2 7 9 6 8]
 [4 5 7 1 2]]

[[ 2  7  9  6  8]
 [ 4  5  7  1  2]
 [-4 -5 -6 -7 -8]]


# * Delete function

In [12]:
a=np.array([12,13,14,15])
print(a)
x=np.delete(a,[2])
print(x)

[12 13 14 15]
[12 13 15]


# * delete in 2D array

In [13]:
a=np.array([[5,6,7,8,9,10],[7,8,1,6,4,6]])
print(a)
print()
b=np.delete(a,0,axis=0)
print(b)

[[ 5  6  7  8  9 10]
 [ 7  8  1  6  4  6]]

[[7 8 1 6 4 6]]


# ##numpy part-7

# 1. matrix
# 2. arithmatic operations in matrix
# 3. matrix functions
a. swapaxes function
b. transpose
c. inverse
d. power
e. Determinate

# *Matrix 

In [14]:
import numpy as np

In [15]:
a=np.matrix([[1,2,3],[1,2,3]])
print(a)
print(type(a))

[[1 2 3]
 [1 2 3]]
<class 'numpy.matrix'>


In [16]:
b=np.array([[1,2,3],[1,2,3]])
print(b)
print(type(b))

[[1 2 3]
 [1 2 3]]
<class 'numpy.ndarray'>


# * Arithmatic operation in matrix

# a. addition

In [17]:
import numpy as np

In [19]:
print("we are talking about matrix")
a=np.matrix([[1,2,3],[1,2,3]])
c=np.matrix([[4,5,6],[4,5,6]])
print(a)
print()
print(c)
print()
print(a+c)

print("we are talking about array")

n=np.array([[1,2,3],[1,2,3]])
m=np.array([[4,5,6],[4,5,6]])
print(n)
print()
print(m)
print()
print(n+m)

we are talking about matrix
[[1 2 3]
 [1 2 3]]

[[4 5 6]
 [4 5 6]]

[[5 7 9]
 [5 7 9]]
we are talking about array
[[1 2 3]
 [1 2 3]]

[[4 5 6]
 [4 5 6]]

[[5 7 9]
 [5 7 9]]


# * substraction

In [20]:
print("we are talking about matrix")
a=np.matrix([[1,2,3],[1,2,3]])
c=np.matrix([[4,5,6],[4,5,6]])
print(a)
print()
print(c)
print()
print(a-c)

print("we are talking about array")

n=np.array([[1,2,3],[1,2,3]])
m=np.array([[4,5,6],[4,5,6]])
print(n)
print()
print(m)
print()
print(n-m)

we are talking about matrix
[[1 2 3]
 [1 2 3]]

[[4 5 6]
 [4 5 6]]

[[-3 -3 -3]
 [-3 -3 -3]]
we are talking about array
[[1 2 3]
 [1 2 3]]

[[4 5 6]
 [4 5 6]]

[[-3 -3 -3]
 [-3 -3 -3]]


# * multiplication

In [24]:
print("we are talking about matrix")
a=np.matrix([[1,2],[3,4]])
b=np.matrix([[5,6],[7,8]])
print(a)
print(type(a))
print()
print(b)
print(type(b))

print()
m=a.dot(b)
print(m)

print("we are talking about array")
m=np.array([[1,2],[3,4]])
n=np.array([[5,6],[7,8]])
print(m)
print()
print(n)
print()
print(m*n)

we are talking about matrix
[[1 2]
 [3 4]]
<class 'numpy.matrix'>

[[5 6]
 [7 8]]
<class 'numpy.matrix'>

[[19 22]
 [43 50]]
we are talking about array
[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[ 5 12]
 [21 32]]


# * devision

In [25]:
print("we are talking about matrix")
a=np.matrix([[1,2],[3,4]])
b=np.matrix([[5,6],[7,8]])
print(a)
print(type(a))
print()
print(b)
print(type(b))

print()
print(b/a)
print(m)

print("we are talking about array")
m=np.array([[1,2],[3,4]])
n=np.array([[5,6],[7,8]])
print(m)
print()
print(n)
print()
print(n/m)

we are talking about matrix
[[1 2]
 [3 4]]
<class 'numpy.matrix'>

[[5 6]
 [7 8]]
<class 'numpy.matrix'>

[[5.         3.        ]
 [2.33333333 2.        ]]
[[1 2]
 [3 4]]
we are talking about array
[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[5.         3.        ]
 [2.33333333 2.        ]]


# * matrix functions

# a. transpose function
interchange of rows, and columns

In [27]:
a=np.matrix([[4,5,6],[14,16,18],[9,17,43]])
print(a)
print()
print(np.transpose(a))

[[ 4  5  6]
 [14 16 18]
 [ 9 17 43]]

[[ 4 14  9]
 [ 5 16 17]
 [ 6 18 43]]


In [28]:
a=np.matrix([[4,5,6],[14,16,18],[9,17,43]])
print(a)
print()
print(a.T)

[[ 4  5  6]
 [14 16 18]
 [ 9 17 43]]

[[ 4 14  9]
 [ 5 16 17]
 [ 6 18 43]]


# b. swapaxis function
work like transpose

In [29]:
a=np.matrix([[4,5,6],[14,16,18],[9,17,43]])
print(a)
print()
print(np.swapaxes(a,1,0))

[[ 4  5  6]
 [14 16 18]
 [ 9 17 43]]

[[ 4 14  9]
 [ 5 16 17]
 [ 6 18 43]]


In [32]:
a=np.matrix([[4,5,6],[14,16,18],[9,17,43]])
print(a)
print()
print(np.swapaxes(a,1,0))
print()
print(np.swapaxes(a,0,1))

[[ 4  5  6]
 [14 16 18]
 [ 9 17 43]]

[[ 4 14  9]
 [ 5 16 17]
 [ 6 18 43]]

[[ 4 14  9]
 [ 5 16 17]
 [ 6 18 43]]


# * inverse function

In [33]:
a=np.matrix([[3,4],[2,1]])
print(a)
print()
print(np.linalg.inv(a))

[[3 4]
 [2 1]]

[[-0.2  0.8]
 [ 0.4 -0.6]]


# * power function

In [36]:
a=np.matrix([[1,2],[4,5]])
print(a)
print()
print(np.linalg.matrix_power(a,2))
print()
print(np.linalg.matrix_power(a,0))
print()
print(np.linalg.matrix_power(a,-2))

[[1 2]
 [4 5]]

[[ 9 12]
 [24 33]]

[[1 0]
 [0 1]]

[[ 3.66666667 -1.33333333]
 [-2.66666667  1.        ]]


# * Determinate function

In [37]:
a=np.matrix([[1,3,5],[2,4,6],[10,11,12]])
print(a)
print()
print(np.linalg.det(a))

[[ 1  3  5]
 [ 2  4  6]
 [10 11 12]]

2.442490654175344e-16
